apiVersion: v1
kind: Pod
metadata:
  name: nginx-dav
  namespace: default
spec:
  containers:
  - name: nginx-dav
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "wholetale/webdav"
      fsType: "webdav"
      options:
        server: "http://10.244.0.27:8080"
